import {afterEach,describe,expect,it,vi} from 'vitest';
import {mkdtemp,mkdir,readFile,rm,stat,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
import {Credentials} from '../../tooling/asset-studio/server/credentials';
import {StudioService} from '../../tooling/asset-studio/server/service';
import {jobRequestSchema} from '../../tooling/asset-studio/shared/schema';
import {processImage} from '../../tooling/asset-studio/server/images';
import {atomic,within,saveJson} from '../../tooling/asset-studio/server/storage';
import {commitFiles,recoverTransactions} from '../../tooling/asset-studio/server/transaction';
import {AmbiguousGeneration,openAIProvider} from '../../tooling/asset-studio/server/provider';
const roots:string[]=[];
const workspace=async()=>{const p=await mkdtemp(path.join(tmpdir(),'asset-studio-test-'));roots.push(p);return p;};
const request=(extra:Record<string,unknown>={})=>jobRequestSchema.parse({submissionId:randomUUID(),name:'Forest heart',slug:'forest-heart',category:'item',prompt:'An amber heart',parameters:{background:'opaque'},...extra});
const png=(w=256,h=256,color='#945211')=>sharp({create:{width:w,height:h,channels:4,background:color}}).png().toBuffer();
afterEach(async()=>{vi.unstubAllEnvs();await Promise.all(roots.splice(0).map(p=>rm(p,{recursive:true,force:true})));});
describe('local credentials and paths',()=>{
 it('stores a key with restrictive permissions and exposes only presence',async()=>{vi.stubEnv('OPENAI_API_KEY','');const root=await workspace(),c=new Credentials(root);expect((await c.status()).configured).toBe(false);await c.set('test-key-not-a-real-credential');expect(await c.status()).toEqual({configured:true,source:'local'});expect((await stat(path.join(root,'.asset-work/credentials.local'))).mode&0o777).toBe(0o600);await c.set('');expect((await c.status()).configured).toBe(false);});
 it('rejects traversal, absolute paths and symlink escapes',async()=>{const root=await workspace(),outside=await workspace();await symlink(outside,path.join(root,'escape'));for(const p of ['../nope','/etc/passwd','escape/secret'])await expect(within(root,p)).rejects.toThrow();});
});
describe('image exports',()=>{
 it('contains a wide source without stretching and publishes exact sRGB PNG dimensions',async()=>{const root=await workspace();await atomic(path.join(root,'source'),await png(512,256));const c=await processImage(root,'source','output.png',request());expect(c.width).toBe(128);expect(c.height).toBe(128);expect(c.alpha!.transparent).toBe(8192);expect(c.errors).toEqual([]);});
 it('rejects tiny inputs, corrupt bytes and opaque fake rims',async()=>{const root=await workspace();await atomic(path.join(root,'tiny'),await png(32,32));await expect(processImage(root,'tiny','out.png',request())).rejects.toThrow('Upscaling');await atomic(path.join(root,'bad'),Buffer.from('not a png'));await expect(processImage(root,'bad','out.png',request())).rejects.toThrow();await atomic(path.join(root,'source'),await png());const c=await processImage(root,'source','out.png',request({profile:'interface-rim',opening:{x:.2,y:.2,width:.6,height:.6}}));expect(c.errors.join(' ')).toContain('Protected opening');});
 it('requires a transparent interior and exterior, allowing painted rim material between',async()=>{const root=await workspace();const source=await sharp({create:{width:256,height:256,channels:4,background:'#00000000'}}).composite([{input:await png(216,216),left:20,top:20},{input:await png(160,160,'#00000000'),left:48,top:48,blend:'dest-out'}]).png().toBuffer();/* Construct an explicit alpha opening using SVG to avoid blend ambiguity. */await atomic(path.join(root,'source'),await sharp(Buffer.from('<svg width="256" height="256"><path d="M20 20H236V236H20Z M48 48V208H208V48Z" fill="#855522" fill-rule="evenodd"/></svg>')).png().toBuffer());expect(source.length).toBeGreaterThan(0);const c=await processImage(root,'source','out.png',request({profile:'interface-rim',opening:{x:.25,y:.25,width:.5,height:.5}}));expect(c.errors).toEqual([]);});
});
describe('review and publication',()=>{
 it('deduplicates submissions, binds approval to bytes, survives workspace cleanup and rejects stale replacement',async()=>{const root=await workspace(),service=new StudioService(root);await service.init();const input=request(),job=await service.create(input,await png());expect((await service.create(input,await png())).id).toBe(job.id);await expect(service.publish(job.id,job.candidates[0].id)).rejects.toThrow('Approve');const c=job.candidates[0];await service.approve(job.id,c.id,c.outputHash!);await service.publish(job.id,c.id);const record=(await service.library())[0];expect(record.outputs[0].path).toBe('assets/icons/item-forest-heart.png');expect((await sharp(await readFile(path.join(root,record.outputs[0].path))).metadata()).width).toBe(128);expect(JSON.stringify(await readFile(path.join(root,record.origin.job!),'utf8'))).not.toContain('.asset-work/jobs');await rm(path.join(root,'.asset-work/jobs'),{recursive:true});const reopened=new StudioService(root);await reopened.init();expect((await reopened.library())[0].revision).toBe(1);const replacement=await reopened.create(request({replaceId:record.id,expectedRevision:7}),await png());const rc=replacement.candidates[0];await reopened.approve(replacement.id,rc.id,rc.outputHash!);await expect(reopened.publish(replacement.id,rc.id)).rejects.toThrow('changed');});
 it('keeps manual import provenance even when style references are selected',async()=>{const root=await workspace(),service=new StudioService(root);await service.init();const first=await service.create(request(),await png());await service.approve(first.id,first.candidates[0].id,first.candidates[0].outputHash!);await service.publish(first.id,first.candidates[0].id);const reference=(await service.library())[0];const second=await service.create(request({slug:'second-heart',references:[{id:reference.id,role:'style'}]}),await png());await service.approve(second.id,second.candidates[0].id,second.candidates[0].outputHash!);await service.publish(second.id,second.candidates[0].id);expect((await service.library()).find(r=>r.id===second.publishedId)!.origin.method).toBe('import');});
 it('invalidates approval after reframing and prevents reading credentials as an image',async()=>{const root=await workspace(),service=new StudioService(root);await service.init();const job=await service.create(request(),await png(512,256)),c=job.candidates[0];await service.approve(job.id,c.id,c.outputHash!);await service.process(job.id,c.id,{fit:'cover',background:'#00000000'});await expect(service.publish(job.id,c.id)).rejects.toThrow('Approve');await expect(service.image('.asset-work/credentials.local')).rejects.toThrow('not in the library');});
 for(const failureAt of [0,1,2])it(`rolls back all files when publication fails at write ${failureAt+1}`,async()=>{const root=await workspace();await atomic(path.join(root,'assets/icon.png'),Buffer.from('old icon'));await atomic(path.join(root,'assets/manifest.json'),Buffer.from('old manifest'));let count=0;await expect(commitFiles(root,[{path:'assets/icon.png',bytes:Buffer.from('new icon')},{path:'art/record.json',bytes:Buffer.from('new record')},{path:'assets/manifest.json',bytes:Buffer.from('new manifest')}],async(file,bytes)=>{if(count++===failureAt)throw Error('disk fault');await atomic(file,bytes);})).rejects.toThrow('disk fault');await recoverTransactions(root);expect(await readFile(path.join(root,'assets/icon.png'),'utf8')).toBe('old icon');expect(await readFile(path.join(root,'assets/manifest.json'),'utf8')).toBe('old manifest');await expect(stat(path.join(root,'art/record.json'))).rejects.toThrow();});
});
describe('provider lifecycle',()=>{
 it('does not automatically retry an ambiguous paid request, including after restart',async()=>{vi.stubEnv('OPENAI_API_KEY','test-only-provider-key');const root=await workspace(),provider=vi.fn(async()=>{throw new AmbiguousGeneration('uncertain');}),service=new StudioService(root,provider);await service.init();const job=await service.create(request());await vi.waitFor(()=>expect(job.state).toBe('unknown'));await service.create(job.request);expect(provider).toHaveBeenCalledTimes(1);const next=new StudioService(root,provider);await next.init();expect(next.get(job.id).state).toBe('unknown');expect(provider).toHaveBeenCalledTimes(1);});
 it('marks interrupted jobs unknown without calling the provider',async()=>{const root=await workspace();await mkdir(path.join(root,'.asset-work/jobs/x'),{recursive:true});await saveJson(path.join(root,'.asset-work/jobs/x/job.json'),{version:1,id:'x',state:'generating',createdAt:'now',updatedAt:'now',request:request(),references:[],candidates:[],prompt:'hello'});const provider=vi.fn(),service=new StudioService(root,provider);await service.init();expect(service.get('x').state).toBe('unknown');expect(provider).not.toHaveBeenCalled();});
 it('sends the exact supported generation parameters without leaking credentials into metadata',async()=>{const root=await workspace(),bytes=await png();let sent:any;const transport=vi.fn(async(_url:any,init:any)=>{sent=JSON.parse(init.body);return new Response(JSON.stringify({data:[{b64_json:bytes.toString('base64')}]}),{status:200,headers:{'x-request-id':'req-test'}});});const input=request({parameters:{background:'transparent',quality:'medium'}});const job:any={request:input,prompt:'actual assembled prompt',references:[]};const result=await openAIProvider(root,transport as typeof fetch)(job,'never-log-this-key',new AbortController().signal,async()=>{});expect(sent.background).toBe('transparent');expect(sent.input_fidelity).toBeUndefined();expect(sent.partial_images).toBeUndefined();expect(JSON.stringify(job)).not.toContain('never-log-this-key');expect(result.requestId).toBe('req-test');});
});
