import {z} from 'zod';

/** Transport-neutral tool contract. Eve, MCP and HTTP all execute this catalogue. */
export const authoringTools = {
 studio_schema: {description:'Discover current engine schemas. Request commands for the operation list, an operation name for its input, or spell/effect/encounter/asset for a document schema.',inputSchema:z.object({section:z.string()}).strict()},
 studio_author: {description:'Execute a validated editor command as commandJson, including op. Shared UI/MCP storage and validation. Responses are compact by default: preview omits repeated definitions, saves return IDs/revisions, discovery is paginated. Use query to search list/catalog/tree results, offset/limit to page, response full for unabridged data. Read/effects.read always return complete documents.',inputSchema:z.object({commandJson:z.string().max(1_000_000),response:z.enum(['compact','full']).default('compact'),query:z.string().max(160).optional(),offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(100).default(12)}).strict()},
 studio_canvas: {description:'Inspect the active editor canvas or capture it as an image. Optionally open a saved spell/effect first. For spells, view focuses the encounter, caster, target, effect alone, or environment. Never discards unsaved user changes.',inputSchema:z.object({workspace:z.enum(['current','spells','effects']),id:z.string(),capture:z.boolean(),view:z.enum(['encounter','caster','target','effect','environment']).optional()}).strict()},
 studio_asset_image: {description:'Inspect pixels of an existing published icon or texture by asset ID and image index. Read-only, no generation charge or mutation. Use again when an earlier image attachment is unavailable. Returns a bounded 512px preview, original dimensions and verified resource hash; no arbitrary URLs or file paths.',inputSchema:z.object({asset:z.string().regex(/^asset\.[a-z0-9.-]+$/),index:z.number().int().min(1).max(64).default(1)}).strict()},
 studio_image: {description:'Generate an original spell icon or effect texture with GPT Image 2.5. Imports a 128px command icon or 512px effect texture and its full-resolution source into Asset Studio and publishes it for immediate use. Transparency is real alpha. A new unique asset ID is required; existing assets are never overwritten.',inputSchema:z.object({id:z.string().regex(/^asset\.[a-z0-9.-]+$/),name:z.string().min(1).max(160),kind:z.enum(['icon','texture']),prompt:z.string().min(10).max(12000),transparent:z.boolean()}).strict()},
} as const;
export type AuthoringToolName=keyof typeof authoringTools;
export const toolRequestSchema=z.object({name:z.enum(['studio_schema','studio_author','studio_canvas','studio_image','studio_asset_image']),input:z.unknown()}).strict();
