import {mountStudioMarkup} from './components/markup';
import {LibraryBrowser} from './libraryTree';
import {z} from 'zod';
import {visualEffectSchema,visualLayerSchema,type VisualEffect,type VisualLayer} from '../../../src/content/effects/schema';
import type {SpellCommand} from '../shared/protocol';
import {EffectStage} from './effectStage';
import {schemaForm,label,type FieldSchema,type Choice} from './schemaForm';
import {BIOMES} from '../../../src/content/biomes';
import {effectImage} from '../../../src/content/abilities/resources';
import {assetUrls} from '../../../src/shared/assets/urls.generated';
const layerSchema=z.toJSONSchema(visualLayerSchema) as FieldSchema;
export class EffectWorkspace{
 readonly element=document.createElement('section');private stage?:EffectStage;private current?:VisualEffect;private revision:string|null=null;private dirty=false;private selected=0;private solo:number|null=null;
 private library:{id:string;name:string;layers:number}[]=[];private textures:Choice[]=[];private debounce?:ReturnType<typeof setTimeout>;private history:VisualEffect[]=[];private future:VisualEffect[]=[];private tree:LibraryBrowser;private externalEpoch=0;private pendingEpoch=0;private pollTimer?:ReturnType<typeof setTimeout>;
 constructor(private command:(c:SpellCommand)=>Promise<any>,private notice:(s:unknown,error?:boolean)=>void,changed:()=>void){
  this.element.className='effects-workspace';mountStudioMarkup(this.element,`<aside class="fx-library"><div class="eyebrow">EFFECT LIBRARY</div><input data-ui="search" placeholder="Search effects…" aria-label="Search effects"><div data-ui="library"></div><button data-ui="new">+ New effect</button></aside><section class="fx-main"><div class="viewbar"><strong data-ui="title">Select an effect</strong><span data-ui="saved"></span><button data-ui="save">Save</button><button data-ui="publish" class="primary">Publish</button></div><div class="fx-viewport"><canvas></canvas><span class="viewport-note">Drag to orbit · Scroll to zoom · source → target</span></div><div class="fx-transport"><button data-ui="restart" class="primary">↻ Restart</button><button data-ui="play">Pause</button><button data-ui="stop">Stop</button><label><input data-ui="repeat" type="checkbox" checked> Repeat preview</label><label><input data-ui="sustain" type="checkbox"> Sustain</label><select data-ui="speed" aria-label="Effect playback speed"><option value=".25">¼×</option><option value=".5">½×</option><option value="1" selected>1×</option><option value="2">2×</option></select><button data-ui="fit">Fit</button><button data-ui="capture">Capture</button></div><div class="fx-timeline"><div class="fx-ruler"><span>PLAYHEAD</span><input data-ui="seek" type="range" min="0" max="400" value="0" aria-label="Effect timeline playhead"><output data-ui="time">0.00s</output></div><div data-ui="tracks"></div></div><div class="fx-environment"><label>Biome<select data-ui="biome"></select></label><label>Endpoint distance<input data-ui="distance" type="number" value="6" min="0" max="30" step=".5"></label><label>Seed<input data-ui="seed" type="number" value="1" min="1" step="1"></label></div></section><aside class="fx-inspector"><div class="inspector-tabs"><button data-ui="layers-tab" class="active">Layers</button><button data-ui="properties-tab">Effect</button></div><div data-ui="layers-panel"><div class="layer-actions"><select data-ui="shape" aria-label="New layer type">${['particles','glow','billboard','burst','streaks','rain','light','ring','pillar','beam','missile','wavefront'].map(s=>`<option>${s}</option>`).join('')}</select><button data-ui="add">+ Layer</button></div><div data-ui="stack"></div><div class="layer-actions"><button data-ui="duplicate">Duplicate</button><button data-ui="remove">Delete</button><button data-ui="undo">Undo</button><button data-ui="redo">Redo</button></div><div data-ui="layer-form"></div></div><div data-ui="properties-panel" hidden></div><div data-ui="validation" role="status" class="validation"></div></aside>`);
  this.tree=new LibraryBrowser('effects',command,id=>void this.load(id).catch(e=>notice(e,true)),e=>notice(e,true));this.q('library').append(this.tree.element);
  const q=<T extends HTMLElement=HTMLElement>(name:string)=>this.q<T>(name);const action=(name:string,fn:()=>void|Promise<void>)=>q(name).onclick=()=>Promise.resolve().then(fn).catch(e=>notice(e,true));
  action('save',async()=>{if(!this.current)return;const creating=this.revision===null;const r=await command({op:'effects.save',document:this.current,expectedRevision:this.revision});this.current=r.document;this.revision=r.revision;this.dirty=false;q('saved').textContent='Saved';if(creating)await this.tree.place(this.current!.id);await this.refreshLibrary();changed();});
  action('publish',async()=>{if(!this.current||this.dirty||!this.revision)throw Error('Save this effect before publishing');await command({op:'effects.publish',id:this.current.id,expectedRevision:this.revision});q('saved').textContent='Published';notice('Published '+this.current.name+' · linked spells use this effect');changed();});
  action('new',()=>this.newEffect());action('add',()=>{if(!this.current)return;this.checkpoint();const shape=q<HTMLSelectElement>('shape').value as VisualLayer['shape'];let id='layer-'+(this.current.layers.length+1);while(this.current.layers.some(l=>l.id===id))id+='-copy';const layer:VisualLayer={id,sustain:false,enabled:true,startTick:0,anchor:'target',shape,colour:'#89baff',accent:'#ffffff',durationTicks:60,count:shape==='particles'?64:shape==='burst'||shape==='rain'?24:1,size:shape==='glow'?2:.4,height:shape==='rain'?8:shape==='streaks'?3:.06};if(['billboard','streaks','rain'].includes(shape)&&this.textures[0])layer.texture={asset:this.textures[0].id,role:'image',index:1};if(shape==='particles')layer.emitter={mode:'burst',lifetimeTicks:48,rate:24,speed:2,speedVariation:.3,direction:{x:0,y:1,z:0},coneDegrees:40,gravity:-1,drag:.3,spawnRadius:.2,startSize:.12,endSize:0,spin:1,fadeIn:.05,fadeOut:.4};if(shape==='rain'){layer.spread=3;layer.fallAngleDegrees=30;layer.impact={durationTicks:12,count:4,size:.12,spread:.6,height:.5,colour:'#429cff',accent:'#d1eaff'};}if(shape==='light'){layer.intensity=35;layer.size=6;layer.height=2;}this.current.layers.push(layer);this.selected=this.current.layers.length-1;this.update(true);});
  action('duplicate',()=>{if(!this.current?.layers[this.selected])return;this.checkpoint();const l=structuredClone(this.current.layers[this.selected]);while(this.current.layers.some(v=>v.id===l.id))l.id+='-copy';this.current.layers.splice(++this.selected,0,l);this.update(true);});action('remove',()=>{if(!this.current)return;this.checkpoint();this.current.layers.splice(this.selected,1);this.selected=Math.max(0,this.selected-1);this.solo=null;this.update(true);});
  action('undo',()=>{const v=this.history.pop();if(v&&this.current){this.future.push(structuredClone(this.current));this.current=v;this.update(true);}});action('redo',()=>{const v=this.future.pop();if(v&&this.current){this.history.push(structuredClone(this.current));this.current=v;this.update(true);}});
  action('restart',()=>{this.stage?.restart();q('play').textContent='Pause';});action('play',()=>{if(this.stage){if(this.stage.playing)this.stage.playing=false;else this.stage.resume();q('play').textContent=this.stage.playing?'Pause':'Play';}});action('stop',()=>{this.stage?.stop();q('play').textContent='Play';});action('fit',()=>this.stage?.fit());action('capture',()=>{if(!this.stage)return;const a=document.createElement('a');a.href=this.stage.capture();a.download='effect.png';a.click();});
  for(const tab of ['layers','properties'])action(tab+'-tab',()=>{q('layers-panel').hidden=tab!=='layers';q('properties-panel').hidden=tab!=='properties';q('layers-tab').classList.toggle('active',tab==='layers');q('properties-tab').classList.toggle('active',tab==='properties');});
  q<HTMLInputElement>('search').oninput=()=>this.renderLibrary();q<HTMLInputElement>('seek').oninput=()=>{if(this.stage){this.stage.playing=false;this.stage.seek(Number(q<HTMLInputElement>('seek').value));q('play').textContent='Play';}};
  q<HTMLInputElement>('repeat').onchange=()=>{if(this.stage)this.stage.repeat=q<HTMLInputElement>('repeat').checked;};q<HTMLInputElement>('sustain').onchange=()=>{if(this.stage){this.stage.sustain=q<HTMLInputElement>('sustain').checked;this.stage.restart();}};q<HTMLSelectElement>('speed').onchange=()=>{if(this.stage)this.stage.speed=Number(q<HTMLSelectElement>('speed').value);};
  q<HTMLInputElement>('distance').onchange=()=>{if(this.stage){this.stage.distance=Number(q<HTMLInputElement>('distance').value);this.stage.seek(this.stage.tick);this.stage.fit();}};q<HTMLInputElement>('seed').onchange=()=>{if(this.stage){this.stage.seed=Number(q<HTMLInputElement>('seed').value);this.stage.restart();}};
  for(const b of BIOMES)q<HTMLSelectElement>('biome').add(new Option(b.name,b.id));q<HTMLSelectElement>('biome').value='vibrant-forest';q<HTMLSelectElement>('biome').onchange=()=>this.stage?.setBiome(q<HTMLSelectElement>('biome').value);
 }
 private q<T extends HTMLElement=HTMLElement>(name:string){return this.element.querySelector<T>(`[data-ui="${name}"]`)!;}
 context(){return {id:this.current?.id??'',dirty:this.dirty};}
 capture(){if(!this.stage)throw Error('Effect canvas is not open');return this.stage.capture();}
 async syncExternal(){const state=await this.command({op:'effects.preview.state'});if(state&&this.stage&&state.document.id===this.current?.id&&!this.dirty){this.current=state.document;this.externalEpoch=state.epoch;this.stage.distance=state.settings.distance;this.stage.seed=state.settings.seed;this.stage.sustain=state.settings.sustain;this.stage.setBiome(state.settings.biome);this.render();this.preview();this.stage.seek(state.tick);this.stage.playing=state.playing;if(state.stopped)this.stage.stop();}}
 async show(id?:string){if(!this.externalEpoch){const state=await this.command({op:'effects.preview.state'});this.externalEpoch=state?.epoch??0;}this.element.hidden=false;if(!this.stage)this.stage=new EffectStage(this.element.querySelector('canvas')!,(tick,end)=>{const seek=this.q<HTMLInputElement>('seek');seek.max=String(Math.ceil(end));seek.value=String(Math.round(tick));this.q('time').textContent=(tick/40).toFixed(2)+'s';for(const track of this.element.querySelectorAll<HTMLElement>('.fx-track'))track.style.setProperty('--playhead',100*tick/end+'%');});await this.refreshLibrary();if(!this.textures.length){const catalog=await this.command({op:'catalog'});this.textures=catalog.textures.map((t:Choice)=>({id:t.id,name:t.name}));}if(id||!this.current){const selected=id??this.library[0]?.id;if(selected)await this.load(selected);}else this.preview();this.pollExternal();}
 private pollExternal(){clearTimeout(this.pollTimer);this.pollTimer=setTimeout(async()=>{if(!this.stage)return;try{const state=await this.command({op:'effects.preview.state'});if(state&&state.epoch!==this.externalEpoch){if(this.dirty){if(this.pendingEpoch!==state.epoch)this.notice('An MCP effect preview is waiting. Save or switch your draft to view it.');this.pendingEpoch=state.epoch;}else{this.externalEpoch=state.epoch;this.current=state.document;this.revision=null;const stored=this.library.find(e=>e.id===state.document.id);if(stored)this.revision=(await this.command({op:'effects.read',id:stored.id})).revision;this.history=[];this.future=[];this.selected=0;this.solo=null;this.stage.distance=state.settings.distance;this.stage.seed=state.settings.seed;this.stage.sustain=state.settings.sustain;this.stage.setBiome(state.settings.biome);this.stage.speed=state.speed;this.stage.repeat=false;this.q<HTMLInputElement>('repeat').checked=false;this.q<HTMLInputElement>('sustain').checked=state.settings.sustain;this.q<HTMLInputElement>('distance').value=String(state.settings.distance);this.q<HTMLInputElement>('seed').value=String(state.settings.seed);this.q<HTMLSelectElement>('biome').value=state.settings.biome;this.q<HTMLSelectElement>('speed').value=String(state.speed);this.tree.select(state.document.id);this.render();this.preview();this.stage.seek(state.tick);this.stage.playing=state.playing;if(state.stopped)this.stage.stop();this.q('saved').textContent='External preview';this.q('play').textContent=this.stage.playing?'Pause':'Play';}}}catch(e){this.notice(e,true);}if(this.stage)this.pollExternal();},500);}
 hide(){clearTimeout(this.pollTimer);this.element.hidden=true;this.stage?.dispose();this.stage=undefined;}
 private async refreshLibrary(){this.library=await this.command({op:'effects.list'});await this.tree.refresh(this.library,this.current?.id);this.renderLibrary();}
 private renderLibrary(){this.tree.search(this.q<HTMLInputElement>('search').value);}

 private async load(id:string){if(this.dirty&&this.current?.id!==id&&!confirm('Discard unsaved effect changes?'))return;const r=await this.command({op:'effects.read',id});this.current=r.document;this.revision=r.revision;this.dirty=false;this.history=[];this.future=[];this.selected=0;this.solo=null;this.tree.select(id);const url=new URL(location.href);url.searchParams.set('effect',id);url.searchParams.set('workspace','effects');history.replaceState(null,'',url);this.render();this.preview();this.stage?.restart();}
 private checkpoint(){if(this.current){this.history.push(structuredClone(this.current));if(this.history.length>40)this.history.shift();this.future=[];}}
 private update(render=false){this.dirty=true;this.q('saved').textContent='Unsaved';if(render)this.render();clearTimeout(this.debounce);this.debounce=setTimeout(()=>this.preview(),160);}
 private preview(){if(!this.current)return;const result=visualEffectSchema.safeParse(this.current);this.q('validation').textContent=result.success?'':result.error.issues.map(e=>e.path.join('.')+': '+e.message).join('\n');if(!result.success)return;const effect=result.data;if(this.solo!==null)effect.layers=effect.layers.filter((_,i)=>i===this.solo);this.stage?.load(effect);this.renderTracks();}
 private renderTracks(){if(!this.current)return;const host=this.q('tracks');host.replaceChildren();const end=Number(this.q<HTMLInputElement>('seek').max)||this.current.durationTicks;this.current.layers.forEach((l,i)=>{const row=document.createElement('button');row.className='fx-track';row.classList.toggle('selected',i===this.selected);const text=document.createElement('span');text.textContent=l.name||l.id;const lane=document.createElement('span');lane.className='fx-track-lane';const bar=document.createElement('i');bar.style.left=100*l.startTick/end+'%';bar.style.width=Math.min(100,100*(l.sustain||this.current!.loop?end-l.startTick:l.shape==='rain'?l.durationTicks/(l.fallSpeed??1)+(l.launchDelayMs??0)/25+(l.impact?.durationTicks??0):l.durationTicks)/end)+'%';bar.style.background=l.colour;bar.style.opacity=l.enabled?'1':'.25';lane.append(bar);row.append(text,lane);row.onclick=()=>{this.selected=i;this.render();};host.append(row);});}
 private render(){if(!this.current)return;this.q('title').textContent=this.current.name;this.q('saved').textContent=this.dirty?'Unsaved':'Saved';const stack=this.q('stack');stack.replaceChildren();this.current.layers.forEach((l,i)=>{const row=document.createElement('div');row.className='layer-row';row.classList.toggle('selected',i===this.selected);const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=l.enabled;enabled.title='Enable layer';enabled.onchange=()=>{this.checkpoint();l.enabled=enabled.checked;this.update();};const select=document.createElement('button');select.textContent=l.name||l.id;select.onclick=()=>{this.selected=i;this.render();};const solo=document.createElement('button');solo.textContent='S';solo.title='Solo layer (preview only)';solo.classList.toggle('active',this.solo===i);solo.onclick=()=>{this.solo=this.solo===i?null:i;this.render();this.preview();};row.append(enabled,select,solo);for(const [text,delta]of [['↑',-1],['↓',1]] as const){const b=document.createElement('button');b.textContent=text;b.disabled=i+delta<0||i+delta>=this.current!.layers.length;b.onclick=()=>{this.checkpoint();const layers=this.current!.layers;[layers[i],layers[i+delta]]=[layers[i+delta],layers[i]];this.selected=i+delta;this.solo=null;this.update(true);};row.append(b);}stack.append(row);});
  const host=this.q('layer-form');host.replaceChildren();const layer=this.current.layers[this.selected];if(layer){const title=document.createElement('h3');title.textContent=label(layer.shape)+' layer';host.append(title);if(layer.texture){const image=document.createElement('img');image.className='texture-preview';try{image.src=assetUrls[effectImage(layer.texture).path];}catch{}image.alt='Layer texture';host.append(image);}const hidden=['id','enabled','shape'];if(layer.shape!=='particles')hidden.push('emitter');
   if(layer.shape!=='rain')hidden.push('fallSpeed','launchDelayMs','fallAngleDegrees','fallAzimuthDegrees','impact');
   if(!['ring','glow','billboard','light'].includes(layer.shape))hidden.push('motion');
   if(!['burst','billboard','streaks','rain','missile','wavefront','particles'].includes(layer.shape))hidden.push('texture');
   const form=schemaForm(layerSchema,layer,{hidden,choices:path=>path.at(-1)==='asset'?this.textures:undefined,change:()=>this.update()});form.addEventListener('focusin',()=>this.checkpoint(),{once:true});host.append(form);}
  const schema=z.toJSONSchema(visualEffectSchema) as FieldSchema;const props=this.q('properties-panel');props.replaceChildren(schemaForm(schema,this.current,{hidden:['layers','schemaVersion','id'],change:()=>this.update()}));const id=document.createElement('p');id.className='hint';id.textContent=this.current.id;props.append(id);this.renderTracks();
 }
 private newEffect(){const dialog=document.createElement('dialog');dialog.className='new-document';dialog.innerHTML='<form method="dialog"><h2>New effect</h2><label>Name<input name="name" value="New effect" required></label><label>Stable ID<input name="id" value="effect.custom.new-effect" required pattern="[a-z][a-z0-9.\\-]+"></label><div><button value="cancel">Cancel</button><button value="create" class="primary">Create</button></div></form>';document.body.append(dialog);dialog.addEventListener('close',()=>{if(dialog.returnValue==='create'){const data=new FormData(dialog.querySelector('form')!);this.current={schemaVersion:1,id:String(data.get('id')),name:String(data.get('name')),description:'',durationTicks:80,loop:false,layers:[]};this.revision=null;this.dirty=true;this.history=[];this.future=[];this.selected=0;this.solo=null;this.render();this.preview();}dialog.remove();});dialog.showModal();}
}
