import {createElement,FolderPlus,FolderPen,FolderInput,FolderMinus,ChevronsUp} from 'lucide';
import {createTree,syncDataLoaderFeature,selectionFeature,hotkeysCoreFeature,dragAndDropFeature,type TreeInstance} from '@headless-tree/core';
import type {LibraryKind,LibraryTree,treeActionSchema} from '../shared/libraryTree';
import type {SpellCommand} from '../shared/protocol';
import type {z} from 'zod';
import {effectImage} from '../../../src/content/abilities/resources';
import {assetUrls} from '../../../src/shared/assets/urls.generated';
type Entry={id:string;name:string;icon?:string};
type Node=Entry&{folder:boolean;parent:string;children:string[]};
/** Shared compact, keyboard-accessible and windowed library backed by Headless Tree. */
export class LibraryBrowser{
 readonly element=document.createElement('div');private viewport=document.createElement('div');private inner=document.createElement('div');private status=document.createElement('div');
 private data:LibraryTree={schemaVersion:1,folders:[],items:{}};private revision='';private entries:Entry[]=[];private nodes=new Map<string,Node>();private tree?:TreeInstance<Node>;private query='';private expandedBeforeSearch?:string[];private selectedId='';private frame=0;private suppressOpen=false;private rows=new Map<string,HTMLDivElement>();
 constructor(private kind:LibraryKind,private command:(c:SpellCommand)=>Promise<any>,private open:(id:string)=>void,private error:(e:unknown)=>void){
  this.element.className='library-browser';const toolbar=document.createElement('div');toolbar.className='tree-toolbar';for(const [title,text,run]of [['New folder',FolderPlus,()=>this.createFolder()],['Rename folder',FolderPen,()=>this.rename()],['Move selected',FolderInput,()=>this.moveDialog()],['Remove empty folder',FolderMinus,()=>this.remove()],['Collapse folders',ChevronsUp,()=>{this.tree?.applySubStateUpdate('expandedItems',['root']);this.tree?.rebuildTree();this.paint();}]] as const){const b=document.createElement('button');b.title=title;b.setAttribute('aria-label',title);b.append(createElement(text,{width:14,height:14}));b.onclick=()=>void Promise.resolve().then(run).catch(error);toolbar.append(b);}
  this.viewport.className='tree-scroll';this.inner.className='tree-inner';this.viewport.append(this.inner);this.status.className='tree-status';this.status.textContent='Select a folder · drag to move';this.element.append(toolbar,this.viewport,this.status);this.viewport.onscroll=()=>this.paint();
 }
 async refresh(entries:Entry[],selected?:string){this.entries=entries;this.selectedId=selected??this.selectedId;const r=await this.command({op:'tree.read',kind:this.kind});this.data=r.tree;this.revision=r.revision;this.rebuild();}
 select(id:string){this.selectedId=id;if(this.tree){const expand=new Set(this.tree.getState().expandedItems);let parent=this.nodes.get(id)?.parent;while(parent&&parent!=='virtual'){expand.add(parent);parent=this.nodes.get(parent)?.parent;}this.tree.applySubStateUpdate('expandedItems',[...expand]);this.tree.setSelectedItems([id]);this.tree.rebuildTree();this.paint();}}
 search(query:string){const next=query.toLowerCase().trim();if(next&&!this.query)this.expandedBeforeSearch=this.tree?.getState().expandedItems?.slice();if(!next&&this.query&&this.expandedBeforeSearch){this.tree?.applySubStateUpdate('expandedItems',this.expandedBeforeSearch);this.expandedBeforeSearch=undefined;}this.query=next;this.rebuild();}
 get folder(){const ids=this.tree?.getState().selectedItems??[];const node=this.nodes.get(ids.at(-1)??'root');return node?.folder?node.id:node?.parent??'root';}
 async place(id:string){if(this.folder==='root')return;await this.mutate({type:'move',ids:[id],parent:this.folder});}
 private rebuild(){
  const expanded=this.tree?.getState().expandedItems??['root','folder.spells','folder.heroes','folder.units'];this.tree?.registerElement(null);this.tree?.setMounted(false);for(const row of this.rows.values())row.remove();this.rows.clear();
  this.nodes.clear();this.nodes.set('virtual',{id:'virtual',name:'',folder:true,parent:'',children:['root']});this.nodes.set('root',{id:'root',name:'root',folder:true,parent:'virtual',children:[]});for(const f of this.data.folders)this.nodes.set(f.id,{...f,folder:true,children:[]});for(const e of this.entries)this.nodes.set(e.id,{...e,folder:false,parent:this.data.items[e.id]??'root',children:[]});
  let allowed:Set<string>|undefined;if(this.query){
   allowed=new Set(['root','virtual']);const matchedFolders=new Set([...this.nodes.values()].filter(n=>n.folder&&(n.name+' '+n.id).toLowerCase().includes(this.query)).map(n=>n.id));
   for(const n of this.nodes.values()){let parent:Node|undefined=n;let matches=(n.name+' '+n.id).toLowerCase().includes(this.query);while(parent&&!matches){matches=matchedFolders.has(parent.id);parent=this.nodes.get(parent.parent);}if(matches){let cur:Node|undefined=n;while(cur&&!allowed.has(cur.id)){allowed.add(cur.id);cur=this.nodes.get(cur.parent);}}}
  }
  for(const n of this.nodes.values()){if(n.id==='root'||n.id==='virtual'||allowed&&!allowed.has(n.id))continue;this.nodes.get(n.parent)?.children.push(n.id);}
  for(const n of this.nodes.values())n.children.sort((a,b)=>{const x=this.nodes.get(a)!,y=this.nodes.get(b)!;return Number(y.folder)-Number(x.folder)||x.name.localeCompare(y.name);});
  const schedule=()=>{cancelAnimationFrame(this.frame);this.frame=requestAnimationFrame(()=>this.paint());};
  this.tree=createTree<Node>({rootItemId:'virtual',indent:14,initialState:{expandedItems:this.query?[...this.nodes.values()].filter(n=>n.folder).map(n=>n.id):expanded,selectedItems:this.selectedId&&(!allowed||allowed.has(this.selectedId))?[this.selectedId]:[],focusedItem:'root'},getItemName:i=>i.getItemData().name,isItemFolder:i=>i.getItemData().folder,dataLoader:{getItem:id=>this.nodes.get(id)!,getChildren:id=>this.nodes.get(id)?.children??[]},features:[syncDataLoaderFeature,selectionFeature,hotkeysCoreFeature,dragAndDropFeature],setState:schedule,setExpandedItems:schedule,setSelectedItems:schedule,setFocusedItem:schedule,setDndState:schedule,canReorder:false,canDrag:items=>items.every(i=>i.getId()!=='root'),canDrop:(items,target)=>{const id=target.item.getId();if(!target.item.isFolder()||id==='virtual')return false;return items.every(i=>{let n=this.nodes.get(id);while(n){if(n.id===i.getId())return false;n=this.nodes.get(n.parent);}return true;});},onDrop:async(items,target)=>{try{await this.mutate({type:'move',ids:items.map(i=>i.getId()),parent:target.item.getId()});}catch(e){this.error(e);}},onPrimaryAction:i=>{if(!i.isFolder()&&!this.suppressOpen)this.open(i.getId());},scrollToItem:item=>{const index=item.getItemMeta().index,top=index*27;if(top<this.viewport.scrollTop||top>this.viewport.scrollTop+this.viewport.clientHeight-27)this.viewport.scrollTop=top;this.paint();}});
  this.tree.setMounted(true);this.tree.rebuildTree();this.bindProps(this.inner,this.tree.getContainerProps(this.kind==='spells'?'Spell folders':'Effect folders'));this.paint();
 }
 private bindProps(element:HTMLElement,props:Record<string,any>){for(const [key,v]of Object.entries(props)){if(key==='ref'){v?.(element);continue;}if(key.startsWith('on')){(element as any)[key.toLowerCase()]=key==='onClick'?(e:MouseEvent)=>{this.suppressOpen=e.ctrlKey||e.metaKey||e.shiftKey;try{v(e);}finally{this.suppressOpen=false;}}:v;continue;}if(v!==undefined&&v!==null)element.setAttribute(key==='tabIndex'?'tabindex':key,String(v));}}
 private paint(){if(!this.tree)return;const items=this.tree.getItems();this.inner.style.height=items.length*27+'px';const start=Math.max(0,Math.floor(this.viewport.scrollTop/27)-6),end=Math.min(items.length,start+Math.ceil((this.viewport.clientHeight||600)/27)+12),shown=new Set(items.slice(start,end).map(i=>i.getId()));for(const [id,row]of this.rows)if(!shown.has(id)){this.tree.getItemInstance(id).registerElement(null);row.remove();this.rows.delete(id);}
  for(let i=start;i<end;i++){const item=items[i],data=item.getItemData();let row=this.rows.get(data.id);if(!row){row=document.createElement('div');row.className='tree-row';row.dataset.id=data.id;const chevron=document.createElement('span');chevron.className='tree-chevron';const icon=document.createElement('span');icon.className='tree-icon';if(data.icon){const img=document.createElement('img');img.alt='';try{img.src=assetUrls[effectImage({asset:data.icon,role:'image',index:1}).path];}catch{}icon.append(img);}else icon.textContent=data.folder?'▱':'✦';const name=document.createElement('span');name.className='tree-name';name.textContent=data.name;row.append(chevron,icon,name);row.title=data.id==='root'?'/':this.path(data.id);this.inner.append(row);this.rows.set(data.id,row);}
   this.bindProps(row,item.getProps());row.style.top=i*27+'px';row.style.paddingLeft=8+Math.max(0,item.getItemMeta().level)*14+'px';row.classList.toggle('selected',item.isSelected());row.classList.toggle('focused',item.isFocused());row.classList.toggle('drop-target',item.isDragTarget());row.querySelector('.tree-chevron')!.textContent=data.folder?(item.isExpanded()?'▾':'▸'):'';
  }
  const count=this.tree.getState().selectedItems?.length??0;this.status.textContent=count>1?`${count} selected · drag or Move`:`${this.entries.length} ${this.kind} · ${this.data.folders.length} folders`;
 }
 private path(id:string){const parts:string[]=[];let n=this.nodes.get(id);while(n&&n.id!=='root'&&n.id!=='virtual'){parts.unshift(n.name);n=this.nodes.get(n.parent);}return '/'+parts.join('/');}
 private async mutate(action:z.infer<typeof treeActionSchema>){try{const r=await this.command({op:'tree.mutate',kind:this.kind,action,expectedRevision:this.revision});this.data=r.tree;this.revision=r.revision;this.rebuild();}catch(e){await this.refresh(this.entries);throw e;}}
 private nameDialog(title:string,value:string,submit:(name:string)=>Promise<void>){const dialog=document.createElement('dialog');dialog.className='new-document';const heading=document.createElement('h2');heading.textContent=title;const form=document.createElement('form');form.method='dialog';const input=document.createElement('input');input.value=value;input.required=true;input.maxLength=80;input.setAttribute('aria-label','Folder name');const actions=document.createElement('div'),cancel=document.createElement('button'),save=document.createElement('button');cancel.textContent='Cancel';cancel.type='button';cancel.onclick=()=>dialog.close();save.textContent='Save';save.className='primary';actions.append(cancel,save);form.append(heading,input,actions);form.onsubmit=e=>{e.preventDefault();void submit(input.value.trim()).then(()=>dialog.close()).catch(this.error);};dialog.append(form);document.body.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();input.select();}
 private createFolder(){const parent=this.folder;this.nameDialog('New folder in '+this.path(parent),'New folder',async name=>{await this.mutate({type:'create',parent,name});this.tree?.getItemInstance(parent).expand();this.paint();});}
 private rename(){const id=this.tree?.getState().selectedItems?.at(-1);const node=id&&this.nodes.get(id);if(!node||!node.folder||id==='root')throw Error('Select a folder to rename');this.nameDialog('Rename folder',node.name,name=>this.mutate({type:'rename',id:node.id,name}));}
 private remove(){const ids=this.tree?.getState().selectedItems??[];if(ids.length!==1)throw Error('Select an empty folder to remove');return this.mutate({type:'remove',id:ids[0]});}
 private moveDialog(){const ids=this.tree?.getState().selectedItems??[];if(!ids.length||ids.includes('root'))throw Error('Select documents or folders to move');const dialog=document.createElement('dialog');dialog.className='new-document';const heading=document.createElement('h2');heading.textContent=`Move ${ids.length} selected`;const select=document.createElement('select');select.setAttribute('aria-label','Destination folder');for(const n of [...this.nodes.values()].filter(n=>n.folder&&n.id!=='virtual').sort((a,b)=>this.path(a.id).localeCompare(this.path(b.id))))select.add(new Option(this.path(n.id),n.id));const move=document.createElement('button');move.textContent='Move';move.className='primary';move.onclick=()=>void this.mutate({type:'move',ids,parent:select.value}).then(()=>dialog.close()).catch(this.error);const cancel=document.createElement('button');cancel.textContent='Cancel';cancel.onclick=()=>dialog.close();dialog.append(heading,select,cancel,move);document.body.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();}
 dispose(){cancelAnimationFrame(this.frame);this.tree?.registerElement(null);this.tree?.setMounted(false);}
}
