import {effectAudio} from '../../../src/render/audio/effectSound';
import {readEffectVolume,setEffectVolume} from '../../../src/shared/settings/audio';
import {studioClient} from './client';
import {mountStudioMarkup} from './components/markup';
import {mountAssistant} from './assistant';
import {LibraryBrowser} from './libraryTree';
import {z} from 'zod';
import {abilitySchema,abilityCasterSchema,presentationSchema} from '../../../src/content/abilities/schema';
import {schemaForm,type FieldSchema} from './schemaForm';
import {EffectWorkspace} from './effectWorkspace';

import {SpellTimeline} from './timeline';
import {IconPicker} from '../../shared/ui/iconPicker';
import {effectImage} from '../../../src/content/abilities/resources';
import {assetUrls} from '../../../src/shared/assets/urls.generated';
import './style.css';
import './theme.css';
import {SpellStage,type ViewMode} from './stage';
import {encounterSettingsSchema,encounterPresets,applyEncounterPreset,encounterPresetId} from '../../../src/content/abilities/encounter';
import {spellCommandSchema,type SpellCommand,type SpellDocument} from '../shared/protocol';
import type {PreviewState} from '../shared/view';
import {BIOMES} from '../../../src/content/biomes';

window.document.documentElement.dataset.profiler='off';
const app=window.document.querySelector<HTMLDivElement>('#app')!;
mountStudioMarkup(app,`
<header><div class="brand"><span class="sigil">✦</span><div><strong>Spell & Effect Studio</strong><small>UNDER THE CANOPY</small></div></div><nav class="workspace-tabs"><button id="workspace-spells" class="active">Spells</button><button id="workspace-effects">Effects</button></nav><div class="document-title"><span id="title">Loading spell…</span><span class="badge" id="saved">Draft</span></div><div class="header-actions"><button id="new">New spell</button><button id="save">Save</button><button id="publish" class="primary">Publish</button></div></header>
<aside class="library"><div class="eyebrow">SPELL LIBRARY</div><input id="search" placeholder="Search spells…" aria-label="Search spells"><div id="library"></div></aside>
<main><div class="viewbar"><div class="tabs">${['encounter','caster','target','effect','environment'].map((v,i)=>`<button data-view="${v}" class="${i===0?'active':''}">${v[0].toUpperCase()+v.slice(1)}</button>`).join('')}</div><button id="fit">Fit view</button><button id="capture" aria-label="Capture image">↗ Capture</button></div>
<div class="encounter-setup"><label for="setup">Setup</label><select id="setup">${encounterPresets.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}<option value="custom" disabled>Custom setup</option></select><span>Resets and respawns the scene</span></div><div class="stage-heading"><h1 id="encounter-title">Loading spell…</h1></div><div class="stage"><canvas id="stage"></canvas><div class="target-instruction" id="target-instruction">Press Cast to start a fresh take.</div><div class="viewport-note">Drag to orbit · Scroll to zoom</div><div id="toast" role="status"></div></div>
<section class="transport"><div class="transport-actions"><button id="cast" class="cast">✦ Cast <kbd>Q</kbd></button><button id="stop">Interrupt</button><button id="toggle-off" hidden>Toggle off</button><button id="reset">↻ Reset</button><span class="divider"></span><button id="play">Pause</button><button id="step">+1 tick</button><select id="speed" aria-label="Playback speed"><option value="0.25">¼ speed</option><option value="0.5">½ speed</option><option value="1" selected>1× speed</option><option value="2">2× speed</option></select><span id="tick">Tick 0</span></div></section><section class="timeline-panel"><div class="timeline-tabs"><button id="timeline-tab" class="active">Timeline</button><button id="events-tab">Events</button><span id="hash"></span></div><div id="timeline-host"></div><div id="event-panel" class="events" hidden><div id="events"></div></div></section></main>
<aside class="inspector"><div class="inspector-tabs"><button data-panel="spell" class="active">Ability</button><button data-panel="encounter">Encounter</button><button data-panel="visuals">Effect links</button></div>
<div id="panel-spell" class="panel"><h2>Spell properties</h2><button id="configure" class="primary wide">Configure all attributes ↗</button><p class="muted">Mechanics run in the actual game simulation.</p><label>Name<input id="name"></label><div id="spell-icon"></div><label>Description<textarea id="description" rows="3"></textarea></label><div class="section-label">RANK VALUES</div><div id="parameters"></div><div class="section-label">CAST LIFECYCLE</div><div class="two"><label>Prepare ticks<input id="prepare" type="number" min="0" max="400"></label><label>Recover ticks<input id="recover" type="number" min="0" max="400"></label></div><button id="apply" class="wide primary">Apply & reset encounter</button><p class="hint">Changes stay in the draft until saved. Publish updates the current spell used by the game.</p><details><summary>Bind published ability to a unit</summary><label>Unit<select id="binding-unit"></select></label><label><input id="binding-hidden" type="checkbox"> AI only (no command button)</label><button id="edit-bindings" class="wide">Configure unit bindings ↗</button><button id="bind-unit" class="wide">Bind published ability</button><p class="hint">Updates the unit definition for future matches. Uses its existing mana pool, or starts one with 200 mana.</p></details><details><summary>Definition JSON</summary><textarea id="json" rows="12" spellcheck="false"></textarea><button id="apply-json">Apply JSON</button></details></div>
<div id="panel-encounter" class="panel" hidden><h2>Test encounter</h2><label>Caster model<select id="caster-model"></select></label><label>Target model<select id="target-model"></select></label><label>Caster nature<select id="caster-nature"><option value="">Authored classification</option><option value="organic">Organic</option><option value="undead">Undead</option><option value="mechanical">Mechanical</option></select></label><label>Target nature<select id="target-nature"><option value="">Authored classification</option><option value="organic">Organic</option><option value="undead">Undead</option><option value="mechanical">Mechanical</option></select></label><label>Caster movement<select id="caster-locomotion"><option value="">Authored movement</option><option value="ground">Ground</option><option value="air">Air</option></select></label><label><input id="caster-hero" type="checkbox"> Caster is a hero</label><label>Target movement<select id="target-locomotion"><option value="">Authored movement</option><option value="ground">Ground</option><option value="air">Air</option></select></label><label><input id="target-hero" type="checkbox"> Targets are heroes</label><label>Ability rank<select id="rank"></select></label><label>Target count<input id="target-count" type="number" min="0" max="8" value="1"></label><label>Target spacing<input id="target-spacing" type="number" min="1" max="8" value="2.5" step=".5"></label><p class="hint">Press Cast, then click a unit or the ground to fire. Units cannot be moved or commanded.</p><label>Target relationship<select id="relationship"><option value="ally">Allies</option><option value="enemy">Enemies</option><option value="self">Self</option><option value="neutral">Neutral camp</option></select></label><label>Distance<input id="distance" type="number" min="1" max="30" value="6"></label><label>Caster health<input id="caster-hp" type="number" min="1" max="5000" value="500" /></label><label>Starting mana<input id="caster-mana" type="number" min="0" max="1000" value="200" /></label><label>Target health<input id="target-hp" type="number" min="1" max="500" value="40"></label><label>Biome<select id="biome"></select></label><label><input id="combat-enabled" type="checkbox"> Combat scenario (units move and fight)</label><label><input id="fallen-targets" type="checkbox"> Start targets as corpses</label><label>Initial target status<select id="initial-status"><option value="">None</option></select></label><div id="status-list" class="hint"></div><button id="apply-encounter" class="primary wide">Reset with these settings</button><div class="section-label">INTERRUPTION TESTS</div><button id="stun" class="wide">Stun caster (1 second)</button><button id="kill-target" class="wide">Remove target</button><button id="kill-caster" class="wide">Remove caster</button><p class="hint">Controls modify this isolated fixture. Production maps are never edited.</p></div>
<div id="panel-visuals" class="panel" hidden><h2>Effect bindings</h2><p class="muted">Connect simulation events to published effects. Edit their visual layers in Effects.</p><div id="cues"></div><button id="apply-visuals" class="primary wide">Apply & reset encounter</button></div></aside>`);
const $=<T extends HTMLElement=HTMLElement>(id:string)=>window.document.getElementById(id) as T;
// External previews can be unsaved without containing local user edits. Only local edits
// block agent navigation; otherwise publication/HMR can strand a stale preview.
let localEdits=false;
let dirty=false,jsonDirty=false,pendingActions=0,updateVersion=0;let actionQueue:Promise<unknown>=Promise.resolve();
let token='',document:SpellDocument,revision:string|null=null,state:PreviewState|undefined,loading=false,disposed=false;
let effectCatalog:{id:string;name:string}[]=[];let workspace:'spells'|'effects'=new URL(location.href).searchParams.get('workspace')==='effects'?'effects':'spells';
let damageTypes:{id:string;name:string}[]=[];let unitCatalog:{id:string;name:string}[]=[];
let settings=applyEncounterPreset(encounterSettingsSchema.parse({combat:false}),'enemy-single'),library:{id:string;name:string;revision:string;icon?:string}[]=[];
function toast(value:unknown,error=false){const node=$('toast');if(workspace==='effects')app.append(node);else window.document.querySelector('.stage')!.append(node);node.textContent=value instanceof Error?value.message:String(value);node.classList.toggle('error',error);node.classList.add('show');setTimeout(()=>node.classList.remove('show'),6000);}
let stage:SpellStage|undefined;
function getStage(){return stage??=new SpellStage($<HTMLCanvasElement>('stage'),error=>toast(error,true),selection=>{if(!state?.targeting)return;pendingActions++;actionQueue=actionQueue.then(async()=>{if(!state?.targeting)return;const result=await command({op:'preview.confirmTarget',target:selection});await update(result.state);if(!result.accepted)toast(result.reason,true);}).catch(e=>toast(e,true)).finally(()=>pendingActions--);});}
const spellTree=new LibraryBrowser('spells',command,id=>void load(id).catch(e=>toast(e,true)),e=>toast(e,true));$('library').append(spellTree.element);
const effectsWorkspace=new EffectWorkspace(command,toast,async()=>{effectCatalog=(await command({op:'effects.library'})).effects.map((e:{id:string;name:string})=>({id:e.id,name:e.name}));if(document&&!localEdits&&!jsonDirty)fill();});app.append(effectsWorkspace.element);effectsWorkspace.element.hidden=true;
async function switchWorkspace(next:'spells'|'effects',effect?:string){workspace=next;app.classList.toggle('effects-active',next==='effects');$('workspace-spells').classList.toggle('active',next==='spells');$('workspace-effects').classList.toggle('active',next==='effects');if(next==='effects'){stage?.dispose();stage=undefined;}const url=new URL(location.href);url.searchParams.set('workspace',next);history.replaceState(null,'',url);if(next==='effects'){await command({op:'preview.play',playing:false,speed:1});await effectsWorkspace.show(effect??(effectsWorkspace.context().id?undefined:new URL(location.href).searchParams.get('effect')??undefined));}else{effectsWorkspace.hide();if(document){const existing=await command({op:'preview.state'});if(existing.loaded&&existing.document.definition.id===document.definition.id)await update(existing);else await reset();fill();}}}
bind('workspace-spells',()=>switchWorkspace('spells'));bind('workspace-effects',()=>switchWorkspace('effects'));
let queuedSeek:number|undefined,seeking=false;
async function seek(tick:number){queuedSeek=tick;if(seeking)return;seeking=true;pendingActions++;try{while(queuedSeek!==undefined){const next=queuedSeek;queuedSeek=undefined;await update(await command({op:'preview.seek',tick:next}));}}catch(e){toast(e,true);}finally{seeking=false;pendingActions--;}}
const timeline=new SpellTimeline(tick=>void seek(tick));$('timeline-host').append(timeline.element);
for(const name of ['timeline','events'])bind(name+'-tab',()=>{$('timeline-host').hidden=name!=='timeline';$('event-panel').hidden=name!=='events';$('timeline-tab').classList.toggle('active',name==='timeline');$('events-tab').classList.toggle('active',name==='events');});
async function command(command:SpellCommand){spellCommandSchema.parse(command);const response=await fetch('/__spells/command',{method:'POST',headers:{'Content-Type':'application/json','X-Spell-Token':token,'X-Studio-Client':studioClient},body:JSON.stringify(command)});const body=await response.json();if(!response.ok)throw Error(body.error??'Spell operation failed');return body;}
function bind(id:string,fn:()=>void|Promise<void>){$(id).addEventListener('click',()=>{pendingActions++;actionQueue=actionQueue.then(()=>{$('toast').classList.remove('show');return fn();}).catch(e=>toast(e,true)).finally(()=>pendingActions--);});}
const input=(id:string)=>$<HTMLInputElement>(id);
const iconPicker=new IconPicker({label:'Command icon',onChange:id=>{if(!document)return;if(id)document.presentation.icon=id;else delete document.presentation.icon;setIcon($('cast'),id||undefined,true);dirty=true;localEdits=true;$('saved').textContent='Unsaved';if(!jsonDirty)input('json').value=JSON.stringify(document,null,2);}});
$('spell-icon').append(iconPicker.element);
function editDocument(){if(jsonDirty)throw Error('Apply the JSON changes first');document.definition.name=input('name').value;if(iconPicker.value)document.presentation.icon=iconPicker.value;else delete document.presentation.icon;document.definition.description=input('description').value;document.definition.cast.prepareTicks=Number(input('prepare').value);document.definition.cast.recoverTicks=Number(input('recover').value);for(const field of documentQuery<HTMLInputElement>('[data-param]'))document.definition.ranks[0][field.dataset.param!]=Number(field.value);dirty=true;localEdits=true;$('saved').textContent='Unsaved';}
function documentQuery<T extends Element>(selector:string){return window.document.querySelectorAll<T>(selector);}
function fill(){
 iconPicker.value=document.presentation.icon??'';setIcon($('cast'),document.presentation.icon,true);
 $('rank').replaceChildren();document.definition.ranks.forEach((_,i)=>{const o=window.document.createElement('option');o.value=String(i+1);o.textContent=`Rank ${i+1}`;$('rank').append(o);});
 $('title').textContent=document.definition.name;$('encounter-title').textContent=document.definition.name;$('encounter-title').title=document.definition.description;input('name').value=document.definition.name;input('description').value=document.definition.description;
 input('prepare').value=String(document.definition.cast.prepareTicks);input('recover').value=String(document.definition.cast.recoverTicks);
 $('parameters').replaceChildren();for(const [name,value]of Object.entries(document.definition.ranks[0])){const label=window.document.createElement('label');label.textContent=name.replace(/([A-Z])/g,' $1');const field=window.document.createElement('input');field.type='number';field.min='0';field.value=String(value);field.dataset.param=name;label.append(field);$('parameters').append(label);}
 input('json').value=JSON.stringify(document,null,2);$('cues').replaceChildren();
 const schema=z.toJSONSchema(presentationSchema) as FieldSchema;
 $('cues').append(schemaForm(schema,document.presentation,{hidden:['schemaVersion','id','icon','animations'],choices:path=>path.at(-1)==='effect'?effectCatalog:undefined,change:()=>{dirty=true;localEdits=true;$('saved').textContent='Unsaved';}}));
 for(const binding of document.presentation.effects){const b=window.document.createElement('button');b.className='wide';b.textContent='Edit '+(effectCatalog.find(e=>e.id===binding.effect)?.name??binding.effect)+' ↗';b.onclick=()=>void switchWorkspace('effects',binding.effect);$('cues').append(b);}
}

async function load(id:string,restore=false){const url=new URL(location.href);url.searchParams.set('spell',id);history.replaceState(null,'',url);const result=await command({op:'read',id});document=result.document;revision=result.revision;dirty=false;localEdits=false;jsonDirty=false;fill();spellTree.select(id);$('saved').textContent='Saved';const existing=restore?await command({op:'preview.state'}):undefined;if(existing?.loaded&&existing.document.definition.id===id){settings=existing.settings;document=existing.document;dirty=JSON.stringify(result.document)!==JSON.stringify(document);fill();await update(existing);}else await reset();}
async function reset(){const result=await command({op:'preview.load',document,settings});await update(result);}
function setIcon(node:HTMLElement,id?:string,cast=false){
 const image=window.document.createElement('img');image.alt='';image.className='command-icon';
 if(id)image.src=assetUrls[effectImage({asset:id,role:'image',index:1}).path];
 if(cast){node.replaceChildren();if(id)node.append(image);node.append(' Cast ');const key=window.document.createElement('kbd');key.textContent='Q';node.append(key);}else if(id)node.replaceChildren(image);else node.textContent='✦';
}
function renderLibrary(){void spellTree.refresh(library,document?.definition.id).catch(e=>toast(e,true));}

async function update(next:PreviewState){const version=++updateVersion;if(!next.loaded)return;const newEpoch=next.epoch!==state?.epoch;
 if(state&&newEpoch&&!localEdits&&!jsonDirty&&JSON.stringify(next.document)!==JSON.stringify(document)){
  const incoming=structuredClone(next.document);let saved:Awaited<ReturnType<typeof command>>|undefined;
  try{saved=await command({op:'read',id:incoming.definition.id});}catch{/* New external draft has no saved revision yet. */}
  // A local edit or a newer preview may arrive while the saved revision is read.
  if(version!==updateVersion||localEdits||jsonDirty)return;
  document=incoming;revision=saved?.revision??null;dirty=!saved||JSON.stringify(saved.document)!==JSON.stringify(incoming);
  fill();$('saved').textContent=dirty?'External preview · Unsaved':'External preview';
 }
 settings=next.settings;state=next;
 if(newEpoch){input('caster-hero').checked=settings.casterHero;input('target-hero').checked=settings.targetHero;input('caster-nature').value=settings.casterNature??'';input('caster-locomotion').value=settings.casterLocomotion??'';input('target-nature').value=settings.targetNature??'';input('target-locomotion').value=settings.targetLocomotion??'';input('combat-enabled').checked=settings.combat;input('fallen-targets').checked=settings.fallenTargets;input('initial-status').value=settings.initialStatuses[0]??'';input('target-count').value=String(settings.targetCount);input('target-spacing').value=String(settings.targetSpacing);input('relationship').value=settings.relationship;input('distance').value=String(settings.distance);input('target-hp').value=String(settings.targetHealth);input('caster-hp').value=String(settings.casterHealth);input('caster-mana').value=String(settings.mana);input('setup').value=encounterPresetId(settings);input('rank').value=String(next.rank);input('biome').value=settings.biome;input('caster-model').value=settings.casterDefinition;input('target-model').value=settings.targetDefinition;}
 if(workspace==='spells')await getStage().update(next);if(version!==updateVersion)return;
 const target=next.entities.find(e=>e.id===next.target);
 $('status-list').textContent=(target?.spellStatuses??[]).map(s=>`${s.status} · ${s.expires===Number.MAX_SAFE_INTEGER?'Until death':Math.max(0,(s.expires-next.tick)/40).toFixed(1)+'s'}`).join(' · ')||'No active target statuses';
 $('cast').hidden=false;$('toggle-off').hidden=!next.document.definition.persistent?.toggle;$<HTMLButtonElement>('toggle-off').disabled=!next.toggleActive;
 $('target-instruction').textContent=next.targeting?(document.definition.targeting.kind==='point'?'Choose ground to cast · Esc cancels':'Choose a unit to cast · Esc cancels'):document.definition.activation==='passive'?'Cast to activate the passive · Reset removes it':document.definition.targeting.kind==='self'?'Cast on the caster · Each cast starts a fresh take':'Cast to reset and choose a new target';
 $('tick').textContent=`${(next.tick/40).toFixed(2)}s`;$('play').textContent=next.playing?'Pause':'Play';$<HTMLButtonElement>('play').disabled=!next.active;$<HTMLButtonElement>('step').disabled=!next.active;$('hash').textContent=`STATE ${next.checksum.toString(16)}`;timeline.update(next);
 const events=$('events');events.replaceChildren();for(const event of next.events.slice(-7).reverse()){const row=window.document.createElement('div');row.className='event';const time=window.document.createElement('span');time.textContent=String(event.tick).padStart(4,'0');const name=window.document.createElement('strong');name.textContent=event.event;const detail=window.document.createElement('span');detail.textContent=event.reason??(event.untilDeath?'Until death':event.amount!==undefined?`${event.amount} ${event.event==='summoned'?'summons':event.event==='dispelled'?'statuses removed':event.event==='statusApplied'?'ticks':event.event==='manaRestored'?'mana':'HP'}`:`Cast #${event.cast}`);row.append(time,name,detail);events.append(row);}
}
bind('cast',async()=>{const r=await command({op:'preview.beginCast'});if(!r.accepted)toast(r.reason,true);await update(r.state);});bind('toggle-off',async()=>{const r=await command({op:'preview.toggleOff'});if(!r.accepted)toast(r.reason,true);await update(r.state);});bind('stop',async()=>{await update(await command({op:'preview.stop'}));});bind('reset',async()=>{await update(await command({op:'preview.reset'}));});bind('play',async()=>{await update(await command({op:'preview.play',playing:!state?.playing,speed:Number(input('speed').value)}));});bind('step',async()=>{await command({op:'preview.play',playing:false,speed:1});await update(await command({op:'preview.step',ticks:1}));});
input('speed').addEventListener('change',()=>command({op:'preview.play',playing:state?.playing??true,speed:Number(input('speed').value)}).catch(e=>toast(e,true)));
bind('fit',()=>getStage().fit());bind('capture',async()=>{const a=window.document.createElement('a');a.href=await getStage().capture();a.download='spell-editor.png';a.click();});
bind('configure',()=>{
 editDocument();const candidate=structuredClone(document),dialog=window.document.createElement('dialog');dialog.className='spell-config';dialog.innerHTML='<div class="config-heading"><h2>Spell configuration</h2><button data-close>×</button></div><div class="config-tabs"><button data-section="mechanics" class="active">Mechanics & ranks</button><button data-section="presentation">Animations & effect links</button></div><div data-form></div><pre data-error role="alert"></pre><footer><button data-cancel>Cancel</button><button data-apply class="primary">Apply & reset preview</button></footer>';
 const render=(section:string)=>{dialog.querySelector('[data-form]')!.replaceChildren(schemaForm(z.toJSONSchema(section==='mechanics'?abilitySchema:presentationSchema) as FieldSchema,section==='mechanics'?candidate.definition:candidate.presentation,{hidden:section==='mechanics'?['schemaVersion','id','presentation']:['schemaVersion','id','icon'],choices:path=>path.at(-1)==='effect'?effectCatalog:(path.at(-1)==='definition'||path.at(-2)==='byRank'&&path.at(-3)==='definition')?unitCatalog:path.at(-1)==='damageType'?damageTypes:undefined,change:()=>{dialog.querySelector('[data-error]')!.textContent='';}}));};
 for(const b of dialog.querySelectorAll<HTMLButtonElement>('[data-section]'))b.onclick=()=>{for(const other of dialog.querySelectorAll('[data-section]'))other.classList.toggle('active',other===b);render(b.dataset.section!);};
 const close=()=>{dialog.close();dialog.remove();};dialog.querySelector<HTMLButtonElement>('[data-close]')!.onclick=close;dialog.querySelector<HTMLButtonElement>('[data-cancel]')!.onclick=close;
 dialog.querySelector<HTMLButtonElement>('[data-apply]')!.onclick=()=>void(async()=>{try{await command({op:'validate',document:candidate});document=candidate;dirty=true;localEdits=true;fill();await reset();$('saved').textContent='Unsaved';close();}catch(e){dialog.querySelector('[data-error]')!.textContent=e instanceof Error?e.message:String(e);}})();app.append(dialog);render('mechanics');dialog.showModal();
});
bind('apply',async()=>{editDocument();await command({op:'validate',document});fill();await reset();toast('Draft applied to encounter');});
bind('apply-json',async()=>{const candidate=JSON.parse(input('json').value);await command({op:'validate',document:candidate});document=candidate;jsonDirty=false;dirty=true;localEdits=true;fill();await reset();$('saved').textContent='Unsaved';});
bind('save',async()=>{editDocument();const creating=revision===null;const result=await command({op:'save',document,expectedRevision:revision});revision=result.revision;document=result.document;dirty=false;localEdits=false;fill();$('saved').textContent='Saved';if(creating)await spellTree.place(document.definition.id);library=await command({op:'list'});renderLibrary();toast('Spell saved');});
bind('publish',async()=>{if(dirty||jsonDirty)throw Error('Save your edits before publishing');if(!revision)throw Error('Save the new spell first');await command({op:'publish',id:document.definition.id,expectedRevision:revision});$('saved').textContent='Published';toast('Published '+document.definition.name);});
bind('edit-bindings',async()=>{
 const selected=input('binding-unit').value,current=await command({op:'binding.read',definition:selected});const candidate=current.caster??{maxMana:200,manaRegenPerSecond:1,bindings:[]};const dialog=window.document.createElement('dialog');dialog.className='spell-config';dialog.innerHTML='<div class="config-heading"><h2>Unit abilities & commands</h2></div><div data-form></div><pre data-error role="alert"></pre><footer><button data-cancel>Cancel</button><button data-apply class="primary">Save unit bindings</button></footer>';
 dialog.querySelector('[data-form]')!.append(schemaForm(z.toJSONSchema(abilityCasterSchema) as FieldSchema,candidate,{choices:p=>p.at(-1)==='ability'?library:undefined,change:()=>{}}));const close=()=>{dialog.close();dialog.remove();};dialog.querySelector<HTMLButtonElement>('[data-cancel]')!.onclick=close;dialog.querySelector<HTMLButtonElement>('[data-apply]')!.onclick=()=>void command({op:'bind',definition:selected,caster:candidate,expectedRevision:current.revision}).then(()=>{close();toast('Unit bindings saved');}).catch(e=>dialog.querySelector('[data-error]')!.textContent=e.message);app.append(dialog);dialog.showModal();
});
bind('bind-unit',async()=>{if(dirty||jsonDirty||!revision)throw Error('Save and publish your ability before binding');const selected=input('binding-unit').value;const current=await command({op:'binding.read',definition:selected});const caster=current.caster??{maxMana:200,manaRegenPerSecond:1,bindings:[]};const hidden=input('binding-hidden').checked;const previous=caster.bindings.find((b:{ability:string})=>b.ability===document.definition.id);const column=[1,2,3,4].find(c=>!caster.bindings.some((b:{ability:string;command?:{column:number}})=>b.ability!==document.definition.id&&b.command?.column===c));if(!hidden&&!column)throw Error('This unit has no free ability command column');caster.bindings=caster.bindings.filter((b:{ability:string})=>b.ability!==document.definition.id).concat({id:previous?.id??document.definition.id.split('.').at(-1),ability:document.definition.id,initialRank:1,controls:hidden?['ai','scenario']:['player','ai','scenario'],...(hidden?{}:{command:{hotkey:['Q','W','E','R'][column!-1],column:column!}}),ai:{preference:'wounded-ally',intervalTicks:12}});await command({op:'bind',definition:selected,caster,expectedRevision:current.revision});toast('Published ability bound to '+selected);});
bind('new',async()=>{const id=window.prompt('Spell ID (e.g. ability.my-pack.sunlight)');if(!id)return;document=structuredClone(document);document.definition.id=id;document.definition.name='New spell';document.presentation.id=id.replace(/^ability\./,'presentation.');document.definition.presentation=document.presentation.id;revision=null;dirty=true;localEdits=true;fill();$('saved').textContent='New draft';await reset();});
bind('apply-encounter',async()=>{settings=encounterSettingsSchema.parse({...settings,casterHero:input('caster-hero').checked,targetHero:input('target-hero').checked,casterNature:input('caster-nature').value||undefined,casterLocomotion:input('caster-locomotion').value||undefined,targetNature:input('target-nature').value||undefined,targetLocomotion:input('target-locomotion').value||undefined,combat:input('combat-enabled').checked,fallenTargets:input('fallen-targets').checked,initialStatuses:input('initial-status').value?[input('initial-status').value]:[],targetCount:Number(input('target-count').value),targetSpacing:Number(input('target-spacing').value),relationship:input('relationship').value,distance:Number(input('distance').value),targetHealth:Number(input('target-hp').value),casterHealth:Number(input('caster-hp').value),mana:Number(input('caster-mana').value),biome:input('biome').value,casterDefinition:input('caster-model').value,targetDefinition:input('target-model').value});await reset();});
bind('stun',async()=>{await update(await command({op:'preview.stun',ticks:40}));});
input('rank').addEventListener('change',()=>command({op:'preview.rank',rank:Number(input('rank').value)}).then(update).catch(e=>toast(e,true)));
bind('kill-target',async()=>{await update(await command({op:'preview.kill',subject:'target'}));});bind('kill-caster',async()=>{await update(await command({op:'preview.kill',subject:'caster'}));});
bind('apply-visuals',async()=>{editDocument();await command({op:'validate',document});fill();await reset();$('saved').textContent='Unsaved';});
function setView(view:ViewMode){for(const b of documentQuery<HTMLButtonElement>('[data-view]'))b.classList.toggle('active',b.dataset.view===view);getStage().setMode(view);}
for(const b of documentQuery<HTMLButtonElement>('[data-view]'))b.addEventListener('click',()=>setView(b.dataset.view as ViewMode));
for(const b of documentQuery<HTMLButtonElement>('.inspector-tabs > button[data-panel]'))b.addEventListener('click',()=>{for(const other of documentQuery('.inspector-tabs > button[data-panel]'))other.classList.toggle('active',other===b);for(const name of ['spell','encounter','visuals'])$('panel-'+name).hidden=name!==b.dataset.panel;});
for(const id of ['panel-spell','panel-visuals'])$(id).addEventListener('input',e=>{dirty=true;localEdits=true;if((e.target as HTMLElement).id==='json')jsonDirty=true;$('saved').textContent='Unsaved';});
input('search').addEventListener('input',()=>spellTree.search(input('search').value));
input('setup').addEventListener('change',()=>{const id=input('setup').value;pendingActions++;actionQueue=actionQueue.then(async()=>{settings=applyEncounterPreset(settings,id);await reset();}).catch(e=>toast(e,true)).finally(()=>pendingActions--);});
window.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;if(workspace!=='spells'||window.document.querySelector('dialog[open],[role=dialog]')||(e.target as HTMLElement).matches('input,textarea,select'))return;if(e.key==='Escape'&&state?.targeting){e.preventDefault();$('reset').click();}if(e.key.toLowerCase()==='q')$('cast').click();if(e.key.toLowerCase()==='r')$('reset').click();if(e.code==='Space'){e.preventDefault();$('play').click();}});
window.addEventListener('beforeunload',()=>{disposed=true;spellTree.dispose();effectsWorkspace.hide();iconPicker.dispose();stage?.dispose();});
// Register capture only after the initial document and its model are ready.
// Capture renders explicitly after scene/resource readiness; waiting for animation
// frames here deadlocks requests when the editor tab is background-throttled.
function startAssistant(){const audioButton=window.document.createElement('button');audioButton.setAttribute('aria-label','Toggle spell audio');const audioLabel=()=>{audioButton.textContent=readEffectVolume()>0?'Sound on':'Sound off';audioButton.setAttribute('aria-pressed',String(readEffectVolume()>0));};audioButton.onclick=()=>{setEffectVolume(readEffectVolume()>0?0:.65);audioLabel();};window.addEventListener('canopy-audio-change',audioLabel);audioLabel();window.setInterval(()=>{const state=readEffectVolume()===0?'muted':effectAudio.context?.state??'waiting for interaction';audioButton.title=`Audio: ${state} · ${effectAudio.voices} active sounds`;audioButton.dataset.audioState=state;audioButton.dataset.activeSounds=String(effectAudio.voices);},250);window.document.querySelector('#app > header')!.append(audioButton);mountAssistant({token,context:()=>({workspace,id:workspace==='spells'?document?.definition.id??'':effectsWorkspace.context().id,dirty:workspace==='spells'?dirty||jsonDirty:effectsWorkspace.context().dirty}),canvas:async action=>{if(action.workspace!=='current'&&(action.workspace!==workspace||action.id)){if(localEdits||jsonDirty||effectsWorkspace.context().dirty)throw Error('Save or discard your unsaved draft before the agent changes the canvas.');if(action.workspace==='effects'){await switchWorkspace('effects',action.id||undefined);await effectsWorkspace.syncExternal();}else{if(workspace!=='spells')await switchWorkspace('spells');if(action.id&&action.id!==document?.definition.id)await load(action.id);}}if(workspace==='effects')await effectsWorkspace.syncExternal();else await update(await command({op:'preview.state'}));if(action.view&&workspace==='spells')setView(action.view);return {workspace,id:workspace==='spells'?document.definition.id:effectsWorkspace.context().id,dirty:workspace==='spells'?dirty||jsonDirty:effectsWorkspace.context().dirty,...(action.capture?{image:await (workspace==='spells'?getStage().capture():effectsWorkspace.capture())}: {})};}});}
async function boot(){const bootstrap=await fetch('/__spells/bootstrap').then(r=>r.json());token=bootstrap.token;const catalog=await command({op:'catalog'});unitCatalog=catalog.units;damageTypes=catalog.damageTypes;effectCatalog=(await command({op:'effects.library'})).effects;for(const status of catalog.statusSpells){const option=window.document.createElement('option');option.value=status.id;option.textContent=status.name;input('initial-status').append(option);}iconPicker.setItems([{id:'',name:'Default unit icon',keywords:['none','automatic']},...catalog.icons.map((icon:{id:string;name:string;keywords?:string[]})=>({...icon,name:icon.name.replace(/\s+spell icon$/i,''),image:assetUrls[effectImage({asset:icon.id,role:'image',index:1}).path]}))]);for(const unit of catalog.units){const o=window.document.createElement('option');o.value=unit.id;o.textContent=unit.name;input('binding-unit').append(o);}for(const name of ['caster','target']as const){for(const unit of catalog.units){const o=window.document.createElement('option');o.value=unit.id;o.textContent=unit.name;input(name+'-model').append(o);}input(name+'-model').value=settings[name==='caster'?'casterDefinition':'targetDefinition'];}for(const biome of BIOMES){const o=window.document.createElement('option');o.value=biome.id;o.textContent=biome.name;input('biome').append(o);}input('biome').value=settings.biome;library=await command({op:'list'});renderLibrary();const requested=new URL(location.href).searchParams.get('spell');await load(library.find(i=>i.id===requested)?.id??library[0].id,true);if(new URL(location.href).searchParams.get('workspace')==='effects')await switchWorkspace('effects',new URL(location.href).searchParams.get('effect')??undefined);}
void boot().then(()=>{startAssistant();const poll=async()=>{if(disposed)return;if(workspace==='spells'&&!loading&&!pendingActions){loading=true;try{let next=await command({op:'preview.state'});if(!next.loaded&&document)next=await command({op:'preview.load',document,settings});await update(next);}catch(e){toast(e,true);}finally{loading=false;}}setTimeout(poll,50);};void poll();}).catch(e=>toast(e,true));
