import {it,expect} from 'vitest';
import {generateKeyPairSync,createHash,sign,randomBytes} from 'node:crypto';
import {verifySignature} from '../../scripts/releases/artifacts';
import {compareVersions,releaseLog} from '../../src/shared/release/schema';
function fixture(){const {privateKey,publicKey}=generateKeyPairSync('ed25519');const key=publicKey.export({format:'der',type:'spki'}).subarray(-32),id=randomBytes(8);const prehash=createHash('blake2b512').update('package').digest(),signature=sign(null,prehash,privateKey),comment='version:0.2.0';const global=sign(null,Buffer.concat([signature,Buffer.from(comment)]),privateKey);return {prehash,pubkey:Buffer.from('untrusted comment: key\n'+Buffer.concat([Buffer.from('Ed'),id,key]).toString('base64')).toString('base64'),signature:Buffer.from('untrusted comment: signature\n'+Buffer.concat([Buffer.from('ED'),id,signature]).toString('base64')+'\ntrusted comment: '+comment+'\n'+global.toString('base64')).toString('base64')};}
it('verifies Tauri/minisign package signatures and rejects damaged packages',()=>{const f=fixture();expect(()=>verifySignature(f.pubkey,f.signature,f.prehash)).not.toThrow();expect(()=>verifySignature(f.pubkey,f.signature,randomBytes(64))).toThrow();expect(()=>verifySignature(fixture().pubkey,f.signature,f.prehash)).toThrow();});
it('rejects tampered trusted metadata, malformed signatures and key identifiers',()=>{const f=fixture();const altered=Buffer.from(Buffer.from(f.signature,'base64').toString().replace('version:0.2.0','version:9.0.0')).toString('base64');expect(()=>verifySignature(f.pubkey,altered,f.prehash)).toThrow();expect(()=>verifySignature(f.pubkey,'abc',f.prehash)).toThrow();});
it('rejects a valid package signature advertised under another release version',()=>{const f=fixture();expect(()=>verifySignature(f.pubkey,f.signature,f.prehash,'0.2.0')).not.toThrow();expect(()=>verifySignature(f.pubkey,f.signature,f.prehash,'0.3.0')).toThrow('expected release version');});
it('compares numeric versions and rejects ambiguous or duplicate release identities',()=>{expect(compareVersions('0.10.0','0.2.0')).toBe(1);expect(()=>compareVersions('01.0.0','1.0.0')).toThrow();expect(releaseLog.safeParse({schemaVersion:1,unreleased:{added:[],improved:[],fixed:[],knownIssues:[]},releases:[{},{}]}).success).toBe(false);});
