import {it,expect,vi} from 'vitest';
import {UpdateController,type PendingUpdate} from '../../src/shared/release/updater';
function fixture(){const update:PendingUpdate={version:'0.2.0',body:'Changes',download:vi.fn(async f=>{f({event:'Started',data:{contentLength:100}});f({event:'Progress',data:{chunkLength:100}});}),install:vi.fn(async()=>{}),close:vi.fn(async()=>{})};const adapter={check:vi.fn(async()=>update as PendingUpdate|null),relaunch:vi.fn(async()=>{})};const changed=vi.fn();return {update,adapter,changed,controller:new UpdateController(adapter,changed)};}
it('checks, downloads and installs only on separate explicit actions',async()=>{const {controller:c,update,adapter}=fixture();await c.check();expect(c.state.phase).toBe('available');expect(update.download).not.toHaveBeenCalled();await c.download();expect(c.state).toMatchObject({phase:'ready',received:100,total:100});expect(update.install).not.toHaveBeenCalled();await c.install();expect(update.install).toHaveBeenCalledTimes(1);expect(adapter.relaunch).toHaveBeenCalledTimes(1);});
it('never installs failed downloads or failed signature verification and allows retry',async()=>{const {controller:c,update}=fixture();vi.mocked(update.download).mockRejectedValueOnce(Error('signature'));await c.check();await c.download();expect(c.state.phase).toBe('available');await c.install();expect(update.install).not.toHaveBeenCalled();await c.download();expect(c.state.phase).toBe('ready');});
it('reports network errors, can recheck, and represents no update correctly',async()=>{const {controller:c,adapter}=fixture();adapter.check.mockRejectedValueOnce(Error('offline'));await c.check();expect(c.state.phase).toBe('error');adapter.check.mockResolvedValueOnce(null);await c.check();expect(c.state.phase).toBe('current');});
it('releases resources for a check that completes after menu disposal',async()=>{const {controller:c,adapter,update}=fixture();let done!:(v:PendingUpdate)=>void;adapter.check.mockImplementationOnce(()=>new Promise(r=>{done=r;}));const check=c.check();await Promise.resolve();await c.dispose();done(update);await check;expect(update.close).toHaveBeenCalledTimes(1);expect(c.state.phase).toBe('checking');});
it('prevents duplicate checks and downloads',async()=>{const {controller:c,adapter,update}=fixture();const first=c.check();await c.check();await first;expect(adapter.check).toHaveBeenCalledTimes(1);let finish!:()=>void;vi.mocked(update.download).mockImplementationOnce(()=>new Promise<void>(r=>{finish=r;}));const download=c.download();await c.download();await c.check();expect(update.download).toHaveBeenCalledTimes(1);expect(adapter.check).toHaveBeenCalledTimes(1);finish();await download;expect(c.state.phase).toBe('ready');});
it('does not restart a failed installation and allows retry',async()=>{const {controller:c,adapter,update}=fixture();vi.mocked(update.install).mockRejectedValueOnce(Error('permission'));await c.check();await c.download();await c.install();expect(c.state.phase).toBe('ready');expect(adapter.relaunch).not.toHaveBeenCalled();await c.install();expect(adapter.relaunch).toHaveBeenCalledTimes(1);});
it('retries restart without reinstalling after installation succeeds',async()=>{const {controller:c,adapter,update}=fixture();adapter.relaunch.mockRejectedValueOnce(Error('restart'));await c.check();await c.download();await c.install();expect(c.state.phase).toBe('restart');await c.restart();expect(update.install).toHaveBeenCalledTimes(1);expect(adapter.relaunch).toHaveBeenCalledTimes(2);});
