import {buildChapter,entity,type Chapter} from './canopyMissionMap';
import type {Placement} from '../../src/content/schema';
const objective=(id:string,title:string,description:string,optional=false)=>({id,title,description,optional});
function camp(entities:Placement[],id:string,x:number,y:number,units:[string,string][],drops:string[]=[],deferred=false){
 const members=units.map(([name,definition],i)=>{entities.push(entity(name,definition,x+(i%2)*3-2,y+Math.floor(i/2)*3,'none',deferred?{activation:'script'}:{}));return name;});
 return {id,members,home:{x,y},aggroRange:10,leash:20,aggression:'players' as const,mapKnowledge:'hidden' as const,fixedDrops:drops};
}
const wolf='unit.neutral.wolf',ogre='unit.neutral.ogre';
const hearth:Placement[]=[entity('mound','building.ants.fort',70,188),entity('marshal','unit.ants.marshal',74,198,'player.1',{initialState:{experience:100}}),entity('guard-one','unit.ants.warrior',77,198),entity('guard-two','unit.ants.warrior',79,197),entity('amber','building.neutral.amber-mine',50,181,'none')];
for(let i=0;i<5;i++)hearth.push(entity(`worker-${i}`,'unit.ants.settler',64+i*2,198));
const hearthCamps=[camp(hearth,'supply-hollow',96,118,[['cache-wolf-one',wolf],['cache-wolf-two',wolf]],['item.trailkeeper-flask']),camp(hearth,'old-gate',183,62,[['gate-ogre',ogre],['gate-wolf-one',wolf],['gate-wolf-two',wolf]],['item.thornband'])];
// A wide authored leash lets the raid pursue the settlement.
for(const [i,id] of ['raider-one','raider-two','raider-three'].entries())hearth.push(entity(id,wolf,113+i*2,162,'none',{activation:'script'}));
hearthCamps.push({id:'hearth-raid',members:['raider-one','raider-two','raider-three'],home:{x:100,y:170},aggroRange:20,leash:96,aggression:'players',mapKnowledge:'hidden',fixedDrops:[]});
const c2:Chapter={id:'vanguard-hearth',name:'Lantern Hearth',description:'Raise a colony in a sheltered clearing. Gather amber and lumber, train your first archers, and secure the road beyond the pond.',seed:4102,start:{x:70,z:188},routes:[[{x:70,z:188},{x:100,z:164},{x:135,z:158},{x:158,z:137},{x:183,z:118},{x:194,z:88},{x:183,z:62}],[{x:100,z:164},{x:83,z:142},{x:96,z:118}]],clearings:[{x:70,z:188,r:25},{x:183,z:62,r:13},{x:96,z:118,r:12}],lakes:[{x:130,z:121,rx:23,rz:21}],entities:hearth,camps:hearthCamps,order:2,cap:4,regions:[{id:'cache',x:96,y:118,radius:15}],objectives:[objective('gather','Stock the Mound','Gather 100 Amber and 60 Lumber. Select workers and right-click the mine or trees; cargo is delivered to the Mound.'),objective('settle','Make room for a colony','Build a Worker House and a Barracks in the clearing.'),objective('archers','Train two Archers','Recruit two Archers at the Barracks. Keep free workers available to enter the building.'),objective('defend','Defend Lantern Hearth','Destroy the three raiders. The Marshal and Mound must survive.'),objective('outpost','Secure the old gate','Follow the lantern road around the pond and defeat the ogre and its two wolves.'),objective('cache','Explore the supply hollow','Clear the side path for a guaranteed Trailkeeper’s Flask.',true)]};
buildChapter(c2);
const root:Placement[]=[entity('mound','building.ants.fort',68,192,'player.1',{initialState:{inventory:{'item.amber':200,'item.wood':100}}}),entity('barracks','building.ants.barracks',85,192),entity('house','building.ants.house',56,195),entity('marshal','unit.ants.marshal',75,201,'player.1',{initialState:{experience:450}}),entity('amber','building.neutral.amber-mine',47,182,'none'),entity('root-vein','building.neutral.corrupted-root',220,66,'none')];
for(let i=0;i<5;i++)root.push(entity(`worker-${i}`,'unit.ants.settler',61+i*2,204));
for(let i=0;i<4;i++)root.push(entity(`warrior-${i}`,'unit.ants.warrior',77+i*2,202));
for(let i=0;i<3;i++)root.push(entity(`archer-${i}`,'unit.ants.archer',78+i*2,205));
const rootCamps=[camp(root,'root-guardians',211,80,[['root-ogre',ogre],['root-wolf-one',wolf],['root-wolf-two',wolf]],['item.barkguard']),camp(root,'old-shell',114,105,[['cache-ogre',ogre]],['item.thornband'])];
for(const [i,[id,definition]] of [['counter-ogre',ogre],['counter-wolf-one',wolf],['counter-wolf-two',wolf],['counter-wolf-three',wolf]].entries())root.push(entity(id,definition,233+i%2*3,91+Math.floor(i/2)*3,'none',{activation:'script'}));
rootCamps.push({id:'root-counterattack',members:['counter-ogre','counter-wolf-one','counter-wolf-two','counter-wolf-three'],home:{x:220,y:86},aggroRange:24,leash:96,aggression:'players',mapKnowledge:'hidden',fixedDrops:[]});
buildChapter({id:'vanguard-root',name:'The Bitter Root',description:'Lead an expedition around the flooded hollow. Hold a corrupted vein, establish a Rootworks, and turn the colony into a Great Mound.',seed:5103,start:{x:68,z:192},routes:[[{x:68,z:192},{x:96,z:182},{x:120,z:168},{x:143,z:151},{x:169,z:143},{x:193,z:121},{x:211,z:97},{x:215,z:70}],[{x:143,z:151},{x:126,z:127},{x:114,z:105}]],clearings:[{x:68,z:192,r:27},{x:216,z:79,r:22},{x:114,z:105,r:12},{x:235,z:93,r:9}],lakes:[{x:159,z:105,rx:29,rz:22}],entities:root,camps:rootCamps,order:3,cap:6,regions:[{id:'root-vein',x:213,y:84,radius:19},{id:'cache',x:114,y:105,radius:15}],objectives:[objective('find-root','Find the corrupted vein','Follow the lantern road around the pond. Keep the Marshal and Mound alive.'),objective('guardians','Clear the Root guardians','Defeat the ogre and two wolves at the vein.'),objective('rootworks','Establish a Rootworks','Build a Rootworks beside the vein, leaving space for workers to approach.'),objective('harvest-root','Bring home 100 Root','Assign workers to the corrupted root. Up to five gather at once; each delivers ten to the Rootworks.'),objective('great-mound','Raise the Great Mound','Upgrade your original Mound using Amber, Lumber and Root.'),objective('hunters','Train two Hunters','Recruit two Hunters at the Barracks and bring the Marshal back to the vein.'),objective('hold-root','Hold the Root clearing','Defeat the incoming ogre and three wolves.'),objective('cache','Explore the old shell','Defeat the lone ogre on the western detour for a guaranteed Thornband.',true)]});
