import {expect,it} from 'vitest';
import {Group,InstancedMesh,Matrix4,Vector3} from 'three';
import {ProjectileEffects} from '../../src/render/settlement/projectileEffects';
import type {GameState} from '../../src/sim/game/state';
import {HeightField} from '../../src/shared';
it('batches authoritative volleys, uses their impact time, and reuses buffers',()=>{
 const parent=new Group(),fx=new ProjectileEffects(parent),field=new HeightField();
 const shot=(id:number,definition='unit.ants.archer'):GameState['missiles'][number]=>({id,source:1,target:2,definition,owner:'player.1',origin:{x:0,y:0},destination:{x:10,y:0},launched:10,impact:22,damage:10,damageType:'piercing',viewers:['player.1'],resolved:false});
 const shots=Array.from({length:200},(_,i)=>shot(i+1));shots.push(shot(201,'unit.neutral.thornspitter'));
 fx.update(16,shots,field);
 expect(fx.root.children).toHaveLength(2);
 const arrows=fx.root.getObjectByName('projectiles.arrow') as InstancedMesh,thorns=fx.root.getObjectByName('projectiles.thorn') as InstancedMesh;
 expect(arrows.count).toBe(200);expect(thorns.count).toBe(1);
 const matrix=new Matrix4(),point=new Vector3();arrows.getMatrixAt(0,matrix);point.setFromMatrixPosition(matrix);
 expect(point.x).toBeCloseTo(5);expect(point.y).toBeCloseTo(field.walkSample(0,0)+1.25+.65);
 expect([...arrows.instanceMatrix.array].every(Number.isFinite)).toBe(true);
 fx.update(22,shots,field);expect(arrows.count).toBe(0);expect(arrows.visible).toBe(false);
 fx.update(24,[{...shot(202),launched:23,impact:35}],field);
 expect(fx.root.getObjectByName('projectiles.arrow')).toBe(arrows);expect(arrows.count).toBe(1);
 fx.dispose();expect(parent.children).toHaveLength(0);
});
