import {describe,it,expect} from 'vitest';
import {readFileSync,readdirSync} from 'node:fs';
import {createBiomeMap} from '../../src/shared/map/newMap';
import {compileMapScene} from '../../src/shared/authoring/mapScene';
import {landscapeAssets} from '../../src/shared/authoring/project';
import {proceduralLayerSchema} from '../../src/shared/authoring/layers';
import {authoredTerrain} from '../../src/render/terrain/authoredTerrain';
import {parseUtcMap} from '../../src/shared/map/utcmap';
import {WalkSurfaces} from '../../src/shared/map/walkSurfaces';
import {bridgeSurfaces,surfaceHeight} from '../../src/shared/map/bridgeSurface';
import {playableMapError} from '../../src/shared/map/playable';
function fixture(){const map=createBiomeMap('Trail',256,'vibrant-forest');map.authoring!.layers=[proceduralLayerSchema.parse({id:'trail',name:'Trail',recipe:'recipe.path.pebbles',seed:1,shape:{type:'mask',strokes:[{operation:'add',radius:10,points:[{x:120,z:128},{x:140,z:128}]}]}})];return map;}
function maskAt(map:ReturnType<typeof fixture>,x:number,z:number){const s=compileMapScene(map,landscapeAssets),t=authoredTerrain(s.field,[],[]);return {value:Buffer.from(t.layers[4]!.mask!,'base64')[(z-s.field.origin)*s.field.verts+x-s.field.origin],texture:t.layers[4]!.ar,scene:s};}
describe('editable pebble trails',()=>{
 it('renders a painted trail and restores underlying ground when subtracted or disabled',()=>{const map=fixture(),before=maskAt(map,130,128);expect(before.value).toBe(255);expect(before.texture).toBe('asset.terrain.pebble-trail');expect(before.scene.generated!.issues).toEqual([]);const l=map.authoring!.layers[0]!;if(l.shape.type==='mask')l.shape.strokes.push({operation:'subtract',radius:4,points:[{x:130,z:128}]});expect(maskAt(map,130,128).value).toBe(0);expect(maskAt(map,122,128).value).toBe(255);l.enabled=false;expect(maskAt(map,122,128).value).toBe(0);});
 it('supports a curved course without flattening the riverbed underneath',()=>{const map=fixture();map.authoring!.layers[0]!.shape={type:'spline',knots:[{x:110,z:128,elevation:9,widthScale:1,depthScale:1,flowScale:1,outgoing:{x:120,z:140}},{x:150,z:128,elevation:9,widthScale:1,depthScale:1,flowScale:1,incoming:{x:140,z:140}}]};const s=compileMapScene(map,landscapeAssets);expect(s.generated!.issues).toEqual([]);expect(s.field.samples.every(n=>n===0)).toBe(true);expect(s.generated!.paint[0]!.weights.some(n=>n===1)).toBe(true);});
 it('ships only the reference forest and all three decks span water with dry exits',()=>{const map=parseUtcMap(JSON.parse(readFileSync('assets/maps/skirmish/threewater-forest.utcmap','utf8')))!;expect(map).toBeTruthy();expect(readdirSync('assets/maps/showcase').filter(f=>f.endsWith('.utcmap'))).toEqual([]);const scene=compileMapScene(map,landscapeAssets);expect(scene.generated!.issues).toEqual([]);expect(scene.resources.length).toBeGreaterThan(1000);expect(playableMapError(map)).toBeNull();const bridges=bridgeSurfaces(scene.stamps,(x,z)=>scene.field.sample(x,z));expect(bridges).toHaveLength(3);const heights=new Int16Array(map.size*map.size),land=new Uint8Array(heights.length);for(let z=0;z<map.size;z++)for(let x=0;x<map.size;x++){heights[z*map.size+x]=Math.round(scene.field.sample(x+.5,z+.5)*100);land[z*map.size+x]=scene.field.wet(x+.5,z+.5)?0:1;}const walk=new WalkSurfaces(map.size,heights,land,bridges);for(const b of bridges){expect(scene.field.wet(b.x,b.z)).toBe(true);expect(surfaceHeight(b,b.x,b.z)).toBeGreaterThan(scene.field.waterAt(b.x,b.z));const ends=[-1,1].map(sign=>({x:Math.floor(b.x+b.s*sign*(b.depth/2+2)),y:Math.floor(b.z+b.c*sign*(b.depth/2+2))}));const route=walk.path(ends[0]!,ends[1]!);expect(route).not.toBeNull();expect(route!.some(n=>n.surface===b.id)).toBe(true);for(const sign of [-1,1]){const z=sign*(b.depth/2-.1),x=b.x+b.s*z,wz=b.z+b.c*z;expect(scene.field.wet(x,wz)).toBe(false);expect(Math.abs(surfaceHeight(b,x,wz)!-scene.field.sample(x,wz))).toBeLessThan(.8);}}},20000);
});
