import {afterEach,expect,it,vi} from 'vitest';
import {EditorScreen} from '../../src/app/game/editorScreen';
import {emptyUtcMap,stringifyUtcMap} from '../../src/shared/map/utcmap';
import {rememberAuthoredMap} from '../../src/shared/map/library';
vi.mock('../../src/shared/map/library',()=>({rememberAuthoredMap:vi.fn()}));
vi.mock('../../src/shared/map/playable',()=>({playableMapError:()=>null}));
afterEach(()=>vi.unstubAllGlobals());
it('saves one immutable snapshot and leaves edits made during the write dirty',async()=>{
 vi.stubGlobal('document',{activeElement:null});vi.stubGlobal('HTMLElement',class {});
 const map=emptyUtcMap(),screen=Object.create(EditorScreen.prototype) as any;
 screen.editor={map,editsReady:async()=>{}};screen.saved='';screen.syncDoc=vi.fn();screen.alert=vi.fn();
 let finish!:()=>void;
 vi.mocked(rememberAuthoredMap).mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve('local:untitled');}));
 const pending=screen.save();await Promise.resolve();
 expect(rememberAuthoredMap).toHaveBeenLastCalledWith(map);
 expect(screen.save()).toBe(pending);
 screen.editor.map={...map,name:'Edited while saving'};finish();
 expect(await pending).toBe(false);
 expect(screen.saved).toBe(stringifyUtcMap(map));expect(screen.dirty()).toBe(true);
 expect(rememberAuthoredMap).toHaveBeenCalledTimes(1);
});
